apiVersion: v1
kind: PersistentVolume
metadata:
  name: f2cfe71af1f79fda-pv
  labels:
    app: clickhouse
    tier: storage
    stack: clickhouse
spec:
  storageClassName: data-backend
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/open-targets-eu-dev/zones/europe-west1-d/disks/f2cfe71af1f79fda-disk
    fsType: ext4
