apiVersion: v1
kind: PersistentVolume
metadata:
  name: ot22d60262e735d8-pv
  labels:
    app: clickhouse
    tier: storage
    stack: clickhouse
    team: open-targets
    subteam: backend
    product: platform
    environment: development
spec:
  storageClassName: data-backend
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/open-targets-eu-dev/zones/europe-west1-d/disks/ot22d60262e735d8-disk
    fsType: ext4
