apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f2cfe71af1f79fda-pvc
  labels:
    app: clickhouse
    tier: storage
    stack: clickhouse
spec:
  storageClassName: data-backend
  volumeName: f2cfe71af1f79fda-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
