apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ot22d60262e735d8-pvc
  labels:
    app: clickhouse
    tier: storage
    stack: clickhouse
    team: open-targets
    subteam: backend
    product: platform
    environment: development
spec:
  storageClassName: data-backend
  volumeName: ot22d60262e735d8-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
