apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
    tier: backend
spec:
  selector:
    app: clickhouse
    tier: backend
  ports:
  - protocol: TCP
    port: 8123
    name: ch-port-b
  - protocol: TCP
    port: 9000
    name: ch-port-a
