apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ot22d60262e735d8-snapshot
  labels:
    app: clickhouse
    tier: storage
    stack: clickhouse
    team: open-targets
    subteam: backend
    product: platform
    environment: development
spec:
  volumeSnapshotClassName: data-backend
  source:
    persistentVolumeClaimName: ot22d60262e735d8-pvc
