apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ot-platform-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opentargets/k8s-gcp-platform.git
    targetRevision: production
    path: kubernetes/overlays/production
  destination:
    namespace: ot-platform-production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true