apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-opensearch
  labels:
    app: opensearch
    tier: storage
spec:
  #storageClassName: data-backend
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi