apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: d676e16a40d19c7b-snapshot
  labels:
    app: opensearch
    tier: storage
    stack: opensearch
    team: open-targets
    subteam: backend
    product: platform
    environment: staging
spec:
  volumeSnapshotClassName: data-backend
  source:
    persistentVolumeClaimName: d676e16a40d19c7b-pvc
