apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-platform
  labels:
    app: ch-platform
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch-platform
      tier: backend
  template:
    metadata:
      labels:
        app: ch-platform
        tier: backend
    spec:
      containers:
      - name: ch-platform
        image: clickhouse/clickhouse-server:23.3.1.2823
        imagePullPolicy: Always
        ports:
        - containerPort: 8123
          name: ch-port-b
        - containerPort: 9000
          name: ch-port-a
        volumeMounts:
          - name: disk-clickhouse
            mountPath: /data_volume
      volumes:
      - name: disk-clickhouse
        persistentVolumeClaim:
          claimName: platform-pvc-source-clickhouse
