apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-pvc-source-clickhouse
  labels:
    app: clickhouse
    tier: storage
spec:
  storageClassName: ssd-small
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi