apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphqlapi-platform
  labels:
    app: graphqlapi-platform
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphqlapi-platform
      tier: backend
  template:
    metadata:
      labels:
        app: graphqlapi-platform
        tier: backend
    spec:
      containers:
      - name: graphqlapi-platform
        image: quay.io/opentargets/platform-api:24.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: gqlapi-port
        env:
        - name: SLICK_CLICKHOUSE_URL
          value: "jdbc:clickhouse://ch-platform:9000"
        - name: ELASTICSEARCH_HOST
          value: "os-platform"
        - name: META_APIVERSION_MAJOR
          value: "0"
        - name: META_APIVERSION_MINOR
          value: "0"
        - name: META_APIVERSION_PATCH
          value: "0"
        - name: META_DATA_YEAR
          value: "23"
        - name: META_DATA_MONTH
          value: "6"
        - name: META_DATA_ITERATION
          value: "0"
        - name: PLATFORM_API_IGNORE_CACHE
          value: "true"
