apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: os-platform
  labels:
    app: os-platform
    tier: backend
spec:
  serviceName: os-platform
  replicas: 3
  selector:
    matchLabels:
      app: os-platform
      tier: backend
  template:
    metadata:
      labels:
        app: os-platform
        tier: backend
    spec:
      containers:
      - name: os-platform
        image: opensearchproject/opensearch:2.10.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          name: os-port-b
        - containerPort: 9300
          name: os-port-a
        env:
        - name: cluster.name
          value: "os-platform"
        - name: discovery.type
          value: "single-node"
        - name: discovery.seed_hosts
          value: "[]"
        - name: bootstrap.memory_lock
          value: "true"
        - name: search.max_open_scroll_context
          value: "5000"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        - name: logger.level
          value: "DEBUG"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms2g -Xmx4g"
        volumeMounts:
          - name: platform-os
            subPath: data
            mountPath: /usr/share/opensearch/data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions: # schedule this where the GCE disk is
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - europe-west1-d
  volumeClaimTemplates:
  - metadata:
      name: platform-os
      labels:
        app: opensearch
        tier: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Gi
      dataSource:
        kind: PersistentVolumeClaim
        name: platform-opensearch
        apiGroup: ""
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
