apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    tier: backend
spec:
  selector:
    app: helloworld
    tier: backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80