apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
    tier: backend
    stack: clickhouse
    team: open-targets
    subteam: backend
    product: platform
    environment: staging
spec:
  selector:
    app: clickhouse
    tier: backend
  ports:
  - protocol: TCP
    port: 8123
    name: ch-port-b
  - protocol: TCP
    port: 9000
    name: ch-port-a
