apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-platform
  labels:
    app: web-platform
    tier: frontend
    team: open-targets
    subteam: backend
    product: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-platform
  template:
    metadata:
      labels:
        app: web-platform
        tier: frontend
        team: open-targets
        subteam: backend
        product: platform
    spec:
      nodeSelector:
        node_type: worker
      tolerations:
      - key: "spot"
        value: "true"
        effect: "PreferNoSchedule"
      containers:
      - name: web-platform
        #image: macbre/nginx-http3:1.23.4
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web-port