apiVersion: v1
kind: Service
metadata:
  name: ch-platform
  labels:
    app: ch-platform
    tier: backend
spec:
  selector:
    app: ch-platform
    tier: backend
  ports:
  - protocol: TCP
    port: 8123
    name: ch-port-secondary
  - protocol: TCP
    port: 9000
    name: ch-port-primary
