apiVersion: v1
kind: Service
metadata:
  name: ch-platform
  labels:
    app: ch-platform
    tier: backend
spec:
  selector:
    app: ch-platform
    tier: backend
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  - protocol: TCP
    port: 9000
    targetPort: 9000
