apiVersion: v1
kind: Service
metadata:
  name: graphqlapi-platform
  labels:
    app: graphqlapi-platform
    tier: backend
spec:
  selector:
    app: graphqlapi-platform
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    name: gqlapi-port