apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-platform
  labels:
    app: os-platform
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-platform
      tier: backend
  template:
    metadata:
      labels:
        app: os-platform
        tier: backend
    spec:
      containers:
      - name: os-platform
        image: opensearchproject/opensearch:2.10.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
        - containerPort: 9300
      env:
      - name: cluster.name
        value: "os-platform"
      - name: discovery.type
        value: "single-node"
      - name: discovery.seed_hosts
        value: "[]"
      - name: bootstrap.memory_lock
        value: "true"
      - name: search.max_open_scroll_context
        value: "5000"
      - name: DISABLE_SECURITY_PLUGIN
        value: "true"
      - name: logger.level
        value: "DEBUG"
      - name: OPENSEARCH_JAVA_OPTS
        value: "-Xms2g -Xmx4g"