apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphqlapi
  labels:
    app: graphqlapi
    tier: backend
    team: open-targets
    subteam: backend
    product: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphqlapi
      tier: backend
  template:
    metadata:
      labels:
        app: graphqlapi
        tier: backend
        team: open-targets
        subteam: backend
        product: platform
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - graphqlapi
            topologyKey: kubernetes.io/hostname
            weight: 20
      resources:
        requests:
          cpu: 400m
          memory: 2Gi
      nodeSelector:
        node_type: worker
      tolerations:
      - key: "spot"
        value: "true"
        effect: "PreferNoSchedule"
      containers:
      - name: graphqlapi
        image: quay.io/opentargets/platform-api:24.1.0-dev.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: gqlapi-port
        env:
        - name: SLICK_CLICKHOUSE_URL
          value: "jdbc:clickhouse://clickhouse:8123"
        - name: ELASTICSEARCH_HOST
          value: "opensearch"
        - name: META_APIVERSION_MAJOR
          value: "0"
        - name: META_APIVERSION_MINOR
          value: "0"
        - name: META_APIVERSION_PATCH
          value: "0"
        - name: META_DATA_YEAR
          value: "24"
        - name: META_DATA_MONTH
          value: "9"
        - name: META_DATA_ITERATION
          value: "0"
        - name: PLATFORM_API_IGNORE_CACHE
          value: "true"
