apiVersion: v1
kind: Service
metadata:
  name: graphqlapi
  labels:
    app: graphqlapi
    tier: backend
    team: open-targets
    subteam: backend
    product: platform
spec:
  selector:
    app: graphqlapi
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    name: gqlapi-port