apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d676e16a40d19c7b-pvc
  labels:
    app: opensearch
    tier: storage
    stack: opensearch
    team: open-targets
    subteam: backend
    product: platform
    environment: development
spec:
  storageClassName: data-backend
  volumeName: d676e16a40d19c7b-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
