apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

components:
  #- ../../../components/platform/production/clickhouse
  #- ../../../components/platform/production/opensearch